"""Service / running-process freshness pre-check (2026-09-16).

Why this module exists
-----------------------
:mod:`binary_freshness` answers "is the compiled artefact on disk newer
than its sources?" — a *build* freshness question. The 2026-09-04
production plan showed the complementary gap: every VP's binary freshness
check PASSED (the ``.so`` on disk WAS fresh), yet VP-001/VP-002 failed
with ``curl: HTTP_CODE:000`` because **nothing was listening on port
8080** — the ``api_server`` process was either dead or running code
from before the last build. Later the same round, VP-019 (whose own
test script did ``pkill + relaunch + wait-for-port``) PASSED, proving
the restart flow works when *somebody* runs it — but nothing ran it
*before* the port-dependent VPs.

This module is the deterministic half of that missing "VP0" step. It
discovers which ports the verification plan depends on, probes whether
a live process holds each port and whether that process post-dates the
newest project source, and decides restart-vs-healthy. The actual
restart (discovery of the start command, kill, relaunch, readiness
wait) lives in :mod:`service_restart_agent`; the orchestration hook is
in ``verification_agent._preflight_service_freshness``.

**Where the port list comes from (2026-09-18).** Originally it was
scraped out of the VP command text by regex, which meant the plan's
dependencies were an emergent property of whatever the planner LLM
typed — ``target_url`` was not even scanned, and three VPs could each
``nohup ... -p 3000 &`` and race for one literal port. The port list
is now the plan's **declared ``services`` block** (see
:mod:`service_declaration`), with the regex scrape retained only for
legacy plans that predate the declaration schema. See
:func:`extract_service_ports` for the branch.

Safety model (learned from a real incident, documented in
``tests/e2e/test_pipeline_e2e.sh`` of the project):
on 2026-09-07 a restart script `kill -9`'d whatever held a port and
**silently murdered the backend on :8000 mid-round**. Therefore:

  * :data:`PROTECTED_PORTS` (the backend + subsidiaries) are filtered
    out at extraction time and refused at every kill site.
  * Killing is further restricted (in the restart agent) to processes
    whose cmdline matches a discovered service pattern; an unknown
    port holder fails loudly instead of being killed blindly.

Everything here is side-effect free: probe / decide / wait only. Never
raises — errors are reported in the returned dataclasses so a broken
probe degrades to "attempt restart" rather than crashing the round.
"""
from __future__ import annotations

import logging
import os
import re
import socket
import subprocess
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Ports owned by the backend runtime itself. A verification round must NEVER
# kill or restart these — doing so severs the orchestrator's own control
# plane (the 2026-09-07 incident: a VP's restart script killed the backend server
# server holding :8000 mid-round and the whole round died silently).
PROTECTED_PORTS = frozenset({8000, 8002, 8003})

_READINESS_TIMEOUT_SECONDS = 30
_READINESS_POLL_INTERVAL = 1.0

# Directories pruned while scanning for the newest source mtime. These
# either contain generated content (target/, node_modules/, .next/,
# dist/, build/, __pycache__) or huge non-source trees (venv/, data
# checkouts under .git/) that would dominate the max-mtime statistic
# without saying anything about *code* freshness.
_SOURCE_PRUNE_DIRS = frozenset({
    ".git", ".hg", ".svn",
    ".venv", "venv", "venv1", "venv2", "env", ".env",
    "site-packages",
    "target", "node_modules", ".next", "nuxt", "dist", "build", "out",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "tmp", "temp", "logs", "log",
    ".idea", ".vscode", ".DS_Store",
})

# Extensions that count as "source / build-input" for the freshness
# comparison. Everything else (data files, images, notebooks' outputs,
# lockfiles generated by the build) is ignored.
_SOURCE_EXTENSIONS = frozenset({
    ".py", ".pyi", ".rs", ".go", ".c", ".cc", ".cpp", ".h", ".hpp",
    ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".java", ".kt", ".cs", ".swift", ".m", ".mm", ".rb", ".php",
    ".toml", ".cfg", ".ini", ".sh", ".bash", ".sql", ".proto",
})


# ---------------------------------------------------------------------------
# Port extraction from the verification plan
# ---------------------------------------------------------------------------

# http(s)://host:port/... — host part stops at the first path slash so
# the capture group only ever sees the port.
_URL_PORT_RE = re.compile(r"https?://[^\s'\"/]+:(\d{2,5})\b")
# Bare host:port literals — the dominant shape in generated test commands.
_HOST_PORT_RE = re.compile(
    r"(?:127\.0\.0\.1|0\.0\.0\.0|localhost|::1|\[::1\]):(\d{2,5})\b"
)
# ``--port 8080`` / ``--port=8080`` / ``-p 8080`` CLI spellings.
_FLAG_PORT_RE = re.compile(r"(?:--port[=\s]+|-p[=\s]+)(\d{3,5})\b")
# ``PORT=8080`` / ``API_PORT=8080`` env spellings.
_ENV_PORT_RE = re.compile(r"\b[A-Z][A-Z0-9_]*PORT=(\d{3,5})\b")


def _iter_plan_text(plan_data: dict) -> List[str]:
    """Collect every string field the planner might have embedded a
    host:port in. VPs are the primary carrier; the round-level
    description/notes are scanned too for cheap completeness.

    ``target_url`` is scanned as of 2026-09-18. It was missing before
    that, and it is the field a ``ui_validation`` VP is *required* to
    carry — so a VP that named its port only there was invisible to the
    preflight and raced an unstarted server.

    ``request.url`` is scanned for the same reason (2026-09-18): an
    ``api_test`` VP states its endpoint there, and without it the
    blocked-port gate below cannot connect a failed service to the VP
    that depends on it — the VP would fire a request at a dead port and
    report a connection error instead of a BLOCKED verdict.
    """
    chunks: List[str] = []
    for key in ("description", "notes", "summary"):
        value = plan_data.get(key)
        if isinstance(value, str):
            chunks.append(value)
    vps = plan_data.get("verification_points") or plan_data.get("vps") or []
    if isinstance(vps, list):
        for vp in vps:
            if not isinstance(vp, dict):
                continue
            for key in (
                "test_command", "description", "title", "command",
                "target_url",
            ):
                value = vp.get(key)
                if isinstance(value, str):
                    chunks.append(value)
            request = vp.get("request")
            if isinstance(request, dict):
                for key in ("url", "body"):
                    value = request.get(key)
                    if isinstance(value, str):
                        chunks.append(value)
    return chunks


def extract_ports_from_text(text: Any) -> set[int]:
    """Every port literal in ``text``, in any of the recognised
    spellings (``http://h:p/``, ``host:p``, ``--port p``/``-p p``,
    ``FOO_PORT=p``).

    Public because both the plan-level declaration validator
    (:mod:`service_declaration`) and the VP command guard need "does
    this string name a port?" without re-deriving the regex set. It is
    a pure string function: no plan shape, no filtering.
    """
    found: set[int] = set()
    if not isinstance(text, str):
        return found
    for regex in (_URL_PORT_RE, _HOST_PORT_RE, _FLAG_PORT_RE, _ENV_PORT_RE):
        for match in regex.finditer(text):
            try:
                port = int(match.group(1))
            except ValueError:  # pragma: no cover - regex guards this
                continue
            if 1 <= port <= 65535:
                found.add(port)
    return found


def _scrape_plan_ports(plan_data: dict) -> set[int]:
    """Every port literal appearing anywhere in the plan's prose or
    VP commands — the pre-2026-09-18 (and still the legacy-plan) source
    of the preflight's port list."""
    found: set[int] = set()
    for chunk in _iter_plan_text(plan_data):
        found |= extract_ports_from_text(chunk)
    return found


def declared_service_ports(
    plan_data: Any, project_dir: Optional[Path] = None
) -> Optional[List[int]]:
    """The plan-level ``services`` declaration's ports, or ``None`` when
    the plan has no ``services`` block at all.

    ``None`` and ``[]`` mean different things and the distinction is
    load-bearing:

      * ``None`` — a legacy plan predating the declaration schema. The
        caller falls back to scraping ports out of command text.
      * ``[]`` — the planner was asked to declare its services and
        declared none. Falling back to scraping here would resurrect
        exactly the "the port list is whatever the LLM typed" behaviour
        the declaration exists to replace, so an empty declaration must
        stay authoritative-empty.
    """
    try:
        # Local import: ``service_declaration`` imports this module for
        # PROTECTED_PORTS and the port regexes, so a module-level import
        # here would be circular.
        from service_declaration import parse_declarations
    except Exception as exc:  # pragma: no cover - defensive
        logger.warning(
            "[service_freshness] service_declaration unavailable (%s); "
            "falling back to scraping ports from command text", exc,
        )
        return None
    try:
        parsed = parse_declarations(plan_data, project_dir or Path.cwd())
    except Exception as exc:  # pragma: no cover - parse never raises
        logger.warning(
            "[service_freshness] service declaration parse failed (%s); "
            "falling back to scraping ports from command text", exc,
        )
        return None
    if not parsed.block_present:
        return None
    return sorted({d.port for d in parsed.declarations})


def extract_service_ports(
    plan_data: dict, project_dir: Optional[Path] = None
) -> List[int]:
    """Return the sorted, de-duplicated, unprotected ports the
    verification plan depends on.

    **Declared services win.** When the plan carries a ``services``
    block, that block *is* the port list — the preflight starts and
    probes exactly what the plan declared, and any port that still
    appears only as a literal in some VP's command text is logged as a
    warning instead of being silently adopted. (Adopting it would mean
    the round manages a service nobody declared and nobody can reap.)

    Legacy plans without a ``services`` block keep the old behaviour:
    scrape every port literal out of the VP commands and round-level
    prose.

    Protected ports (the backend runtime's own) are dropped on both paths — a
    plan that references :8000 is referencing the orchestrator itself,
    and the preflight must never "restart freshness" on it.
    """
    declared = declared_service_ports(plan_data, project_dir)
    if declared is not None:
        scraped = _scrape_plan_ports(plan_data) - PROTECTED_PORTS
        undeclared = sorted(scraped - set(declared))
        if undeclared:
            logger.warning(
                "[service_freshness] verification plan declares services "
                "%s but also references undeclared port(s) %s in command "
                "text; those are NOT managed by the preflight — declare "
                "them in the plan's 'services' block if they need to be "
                "live",
                declared, undeclared,
            )
        return declared

    found = _scrape_plan_ports(plan_data)
    protected = found & PROTECTED_PORTS
    if protected:
        logger.warning(
            "[service_freshness] ignoring protected port(s) %s referenced "
            "by the verification plan (backend runtime ports are never "
            "restarted by the preflight)",
            sorted(protected),
        )
    return sorted(found - PROTECTED_PORTS)


# ---------------------------------------------------------------------------
# Port probing
# ---------------------------------------------------------------------------


@dataclass
class PortProbe:
    """Snapshot of who (if anyone) holds a TCP listening port."""

    port: int
    listening: bool = False
    pids: List[int] = field(default_factory=list)
    cmdlines: List[str] = field(default_factory=list)
    # Earliest process-start epoch among the listeners — the comparison
    # baseline against the newest source mtime. None when unknown
    # (ps failed or the platform rejected the query).
    process_start_epoch: Optional[float] = None
    error: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "port": self.port,
            "listening": self.listening,
            "pids": list(self.pids),
            "cmdlines": list(self.cmdlines),
            "process_start_epoch": self.process_start_epoch,
            "error": self.error,
        }


def _run_probe_cmd(argv: List[str], timeout: int = 10) -> Optional[str]:
    """Run a probe command, returning stripped stdout or None on any
    failure. Probes must never raise — a missing ``lsof``/``ps`` only
    degrades the freshness decision, it must not crash the round."""
    try:
        out = subprocess.run(
            argv, capture_output=True, text=True, timeout=timeout,
        )
        return out.stdout.strip()
    except Exception as exc:  # noqa: BLE001 - probe best-effort by design
        logger.debug("[service_freshness] probe cmd %s failed: %s", argv, exc)
        return None


def probe_port(port: int) -> PortProbe:
    """Identify the process(es) listening on ``port`` (if any).

    Uses ``lsof -ti :PORT`` for the PID list, then ``ps`` for cmdline
    and start time. Any step failing degrades to a partial probe with
    ``error`` set — callers treat an unprobed port as restart-worthy.
    """
    probe = PortProbe(port=port)
    if port in PROTECTED_PORTS:
        probe.error = f"port {port} is a protected backend-runtime port"
        return probe

    pids_out = _run_probe_cmd(["lsof", "-ti", f":{port}"])
    if pids_out is None:
        probe.error = "lsof probe failed (tool missing or errored)"
        return probe

    pids: List[int] = []
    for token in pids_out.split():
        try:
            pids.append(int(token))
        except ValueError:
            continue
    if not pids:
        return probe  # not listening — no error, just absent

    probe.listening = True
    probe.pids = pids

    starts: List[float] = []
    for pid in pids:
        cmdline = _run_probe_cmd(["ps", "-p", str(pid), "-o", "command="])
        if cmdline:
            probe.cmdlines.append(cmdline)
        lstart = _run_probe_cmd(["ps", "-p", str(pid), "-o", "lstart="])
        if lstart:
            epoch = _parse_ps_lstart(lstart)
            if epoch is not None:
                starts.append(epoch)
    probe.process_start_epoch = min(starts) if starts else None
    return probe


def _parse_ps_lstart(raw: str) -> Optional[float]:
    """Parse ``ps -o lstart=`` output (``Thu Sep  4 09:32:01 2026``)."""
    raw = raw.strip()
    if not raw:
        return None
    for fmt in ("%a %b %d %H:%M:%S %Y", "%a %b %e %H:%M:%S %Y"):
        try:
            return datetime.strptime(raw, fmt).timestamp()
        except ValueError:
            continue
    return None


# ---------------------------------------------------------------------------
# Newest source mtime
# ---------------------------------------------------------------------------


def newest_project_source_mtime(project_dir: Path) -> Optional[float]:
    """Newest mtime among source files, pruning generated/vendor trees.

    This is the "code changed at" timestamp the restart decision compares
    against the listener's process start time. Returns None when the
    tree has no recognisable source files (e.g. a docs-only project) —
    callers then fall back to "restart only when no listener".
    """
    project_dir = Path(project_dir)
    if not project_dir.is_dir():
        return None
    newest: Optional[float] = None
    for root, dirs, files in os.walk(project_dir):
        dirs[:] = [
            d for d in dirs
            if d not in _SOURCE_PRUNE_DIRS and not d.startswith(".")
        ]
        for name in files:
            if Path(name).suffix.lower() not in _SOURCE_EXTENSIONS:
                continue
            try:
                mtime = (Path(root) / name).stat().st_mtime
            except OSError:
                continue
            if newest is None or mtime > newest:
                newest = mtime
    return newest


# ---------------------------------------------------------------------------
# Decision
# ---------------------------------------------------------------------------

# Decision vocabulary returned by :func:`classify_probe`.
DECISION_RESTART = "restart"
DECISION_HEALTHY = "healthy"


def classify_probe(
    probe: PortProbe,
    newest_source_mtime: Optional[float],
) -> str:
    """Decide whether the service on ``probe.port`` must be restarted.

    Rules, in order:
      1. No listener → RESTART. A port the plan depends on that nobody
         holds can only be fixed by starting the service.
      2. Probe errored (lsof/ps unavailable) → RESTART. The restart
         agent re-verifies readiness independently, so an unnecessary
         restart is recoverable; a wrongly-skipped one is not.
      3. Listener predates the newest source mtime → RESTART. The
         classic "rebuilt the binary but the server still runs the old
         code" case.
      4. Otherwise → HEALTHY.
    """
    if probe.port in PROTECTED_PORTS:
        return DECISION_HEALTHY  # extraction already filters; belt here
    if not probe.listening:
        return DECISION_RESTART
    if probe.error:
        return DECISION_RESTART
    if (
        newest_source_mtime is not None
        and probe.process_start_epoch is not None
        and probe.process_start_epoch < newest_source_mtime
    ):
        return DECISION_RESTART
    return DECISION_HEALTHY


# ---------------------------------------------------------------------------
# Readiness wait
# ---------------------------------------------------------------------------


def wait_for_ready(
    port: int,
    timeout_seconds: int = _READINESS_TIMEOUT_SECONDS,
    poll_interval: float = _READINESS_POLL_INTERVAL,
    host: str = "127.0.0.1",
) -> bool:
    """Poll a TCP connect to ``host:port`` until it accepts or the
    timeout elapses. TCP-accept is the readiness signal — an HTTP
    server that accepts connections is past bind()/listen(); deeper
    health semantics are the restart agent's business."""
    if port in PROTECTED_PORTS:
        return False  # never "wait ready" on the backend runtime's own ports
    deadline = time.monotonic() + timeout_seconds
    while True:
        try:
            with socket.create_connection((host, port), timeout=2):
                return True
        except OSError:
            pass
        if time.monotonic() >= deadline:
            return False
        time.sleep(poll_interval)


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------


@dataclass
class ServiceFreshnessReport:
    """Per-round summary of the service-freshness preflight."""

    ports_requested: List[int] = field(default_factory=list)
    probes: List[PortProbe] = field(default_factory=list)
    decisions: Dict[int, str] = field(default_factory=dict)
    newest_source_mtime: Optional[float] = None
    # action: "noop" (no ports) | "healthy" (all healthy) |
    #        "restarted" | "blocked" (handled by the restart agent layer)
    action: str = "noop"
    detail: str = ""

    @property
    def needs_restart(self) -> List[int]:
        return sorted(
            port for port, dec in self.decisions.items()
            if dec == DECISION_RESTART
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ports_requested": list(self.ports_requested),
            "probes": [p.to_dict() for p in self.probes],
            "decisions": dict(self.decisions),
            "newest_source_mtime": self.newest_source_mtime,
            "action": self.action,
            "detail": self.detail,
        }


def assess_service_freshness(
    project_dir: Path,
    plan_data: dict,
) -> ServiceFreshnessReport:
    """Pure assessment: extract → probe → decide. No side effects.

    The caller (verification_agent preflight) turns ``needs_restart``
    into an actual restart via :mod:`service_restart_agent` and then
    re-probes to mark the report ``restarted``/``blocked``.
    """
    report = ServiceFreshnessReport()
    # ``project_dir`` is threaded through so the declared-services path
    # can validate each declaration's ``cwd``/``log_path`` containment
    # against the project it will actually run in.
    report.ports_requested = extract_service_ports(plan_data, project_dir)
    if not report.ports_requested:
        report.action = "noop"
        report.detail = "verification plan references no service ports"
        return report

    report.newest_source_mtime = newest_project_source_mtime(project_dir)
    for port in report.ports_requested:
        probe = probe_port(port)
        report.probes.append(probe)
        report.decisions[port] = classify_probe(
            probe, report.newest_source_mtime,
        )

    needed = report.needs_restart
    if needed:
        report.action = "restart_pending"
        report.detail = f"restart required for port(s) {needed}"
    else:
        report.action = "healthy"
        report.detail = "all referenced service ports are live and fresh"
    return report
