"""Unit tests for VP-001, VP-011 and VP-012: Verification Agent Plan/Execution/Report.

Validates that verification_plan.json generated by VerificationAgent is
schema-valid (VP-011): each verification point has all required fields,
priority values are restricted to {high, medium, low}, and
verification_method is one of ``verification_subagent.SUPPORTED_METHODS``.

2026-09-18: the method enum used to be {automated_test, code_review,
ui_validation, api_test, manual_check}. The first two were retired that
day; the sets below are derived from ``SUPPORTED_METHODS`` so this file
cannot drift from the registry again.

Also validates Phase 2 (execute) and Phase 3 (report) contracts
(VP-012): execute_verification_plan returns the expected envelope,
generate_verification_report emits overall_status in {PASSED, FAILED,
LOOP_STOPPED}, per-VP counts sum to total VPs, and
requirement_deviations is a list.

VP-001's Phase-1 "keep vs drop" question is moot now: ``manual_check``
was retired, and an unsupported method is instead marked ``obsolete`` by
``VerificationAgent._normalize_legacy_methods`` — see the tests for that
method.
"""

import json
import tempfile
import shutil
from pathlib import Path
from unittest.mock import Mock

import pytest

from verification_agent import VerificationAgent


from verification_subagent import SUPPORTED_METHODS

VALID_METHODS = set(SUPPORTED_METHODS)
VALID_PRIORITIES = {"high", "medium", "low"}

REQUIRED_VP_FIELDS = [
    "id",
    "title",
    "related_prd_criteria",
    "verification_method",
    "priority",
    "expected_result",
]

# Every supported method survives Phase 1; there is no drop list any more.
KEPT_METHODS = set(SUPPORTED_METHODS)


@pytest.fixture
def temp_plan_dir():
    tmp = tempfile.mkdtemp()
    plan_dir = Path(tmp) / "vp012-plan"
    plan_dir.mkdir(parents=True, exist_ok=True)
    yield plan_dir
    shutil.rmtree(tmp)


@pytest.fixture
def temp_project_dir():
    tmp = tempfile.mkdtemp()
    project_dir = Path(tmp) / "vp012-project"
    project_dir.mkdir(parents=True, exist_ok=True)
    yield project_dir
    shutil.rmtree(tmp)


@pytest.fixture
def mock_coding_tool():
    tool = Mock()
    tool.query_json.return_value = {
        "verdict": "PASSED",
        "reasons": ["ok"],
        "evidence": ["out"],
    }
    return tool


@pytest.fixture
def verification_agent(temp_plan_dir, temp_project_dir, mock_coding_tool):
    # Wire an in-memory SQLite verification repo so the agent can
    # persist Phase 1 execution envelopes to ``plan_verification.execution_results``
    # (task #3.5) instead of the legacy on-disk cache.
    import sqlite3
    from state_machine.db.connection import open as open_db
    from state_machine.db.schema import migrate
    from state_machine.repositories.verification_repository import (
        VerificationRepository,
    )

    db_path = temp_plan_dir.parent / "state.db"
    conn = open_db(db_path)
    migrate(conn)
    repo = VerificationRepository(conn)
    plan_id = temp_plan_dir.name

    # The verification row must exist before the agent can write to it
    # (``_update`` raises KeyError when ``cursor.rowcount == 0``). Seed it
    # once via the repository's ``insert`` helper.
    repo.insert(plan_id, verification_status="not_started")
    conn.commit()

    agent = VerificationAgent(
        plan_dir=temp_plan_dir,
        project_dir=temp_project_dir,
        coding_tool=mock_coding_tool,
        verif_repo=repo,
    )
    # Open a verification round so the persistence layer has an active
    # log file. ``execute_verification_plan`` calls
    # ``persistence.write_verification_point_log`` for every VP, which
    # raises ``RuntimeError("No log file active...")`` if no round is
    # open. ``start_verification_round`` is the canonical entry point.
    agent.start_verification_round(1)
    return agent


def _build_plan_payload(*, methods, priorities):
    vps = []
    for idx, (method, priority) in enumerate(zip(methods, priorities), start=1):
        vp = {
            "id": f"VP-{idx:03d}",
            "title": f"Verification point {idx}",
            "related_prd_criteria": "Relevant PRD criterion",
            "verification_method": method,
            "priority": priority,
            "expected_result": "Expected outcome",
        }
        # api_test VPs must carry a runnable request/assertions envelope
        # so the deterministic runner can grade them (the 2026-09
        # ``repair-r4-01`` gate rejects plans whose api_test VPs lack
        # either half). The earlier fixture omitted both, and the gate
        # then tripped before the assertions below could run.
        if method == "api_test":
            vp["request"] = {
                "method": "GET",
                "url": "{{svc.example.url}}/api/items",
            }
            vp["assertions"] = [{"status": 200}]
        vps.append(vp)
    return {"verification_points": vps}


async def _stub_code_review_async(vp, vp_id=None):
    """Async stub that returns a PASSED result dict for one VP.

    Bound to the agent instance via
    ``type(executor).__name__ == 'function'`` so the per-VP dispatcher
    in :meth:`_run_single_vp_async` detects the patch (the canonical
    class-defined method has ``type.__name__ == 'method'``) and uses
    this stub instead of the canonical sub-agent path. The dispatcher
    then awaits ``_execute_automated_test(vp)`` — we provide a sync
    shim that returns the same dict directly so no extra ``await``
    machinery is needed.
    """
    return {
        "id": vp.get("id", "unknown"),
        "status": "PASSED",
        "actual_result": "stub ok",
        "reasons": ["stub"],
        "evidence": "stub",
    }


def _stub_code_review_sync(vp, vp_id=None):
    """Sync shim paired with ``_stub_code_review_async``.

    The dispatcher awaits ``_execute_automated_test(vp)`` after
    detecting the async-version patch, so this shim must return the
    same shape directly.
    """
    return _stub_code_review_async.__wrapped__(vp) if hasattr(
        _stub_code_review_async, "__wrapped__"
    ) else {
        "id": vp.get("id", "unknown"),
        "status": "PASSED",
        "actual_result": "stub ok",
        "reasons": ["stub"],
        "evidence": "stub",
    }


def _install_code_review_stub(agent):
    """Patch the per-method executor on the agent instance.

    The dispatcher probes ``_execute_<method>_async`` first, then
    ``_execute_<method>``, and requires ``type(executor).__name__ ==
    'function'`` (a class-defined bound method is ``'method'``). The
    async spelling is the one that is awaited, so that is what gets
    patched here.
    """
    agent._execute_code_review_async = _stub_code_review_async


def test_generate_verification_plan(verification_agent, mock_coding_tool,
                                    temp_plan_dir):
    mock_coding_tool.query_json.return_value = _build_plan_payload(
        methods=["code_review", "ui_validation", "api_test"],
        priorities=["high", "medium", "low"],
    )

    plan = verification_agent.generate_verification_plan()

    assert isinstance(plan, dict)
    assert "verification_points" in plan
    assert isinstance(plan["verification_points"], list)
    assert len(plan["verification_points"]) == 3

    plan_path = temp_plan_dir / "verification_plan.json"
    assert plan_path.exists(), "verification_plan.json must be persisted"

    with open(plan_path) as f:
        on_disk = json.load(f)
    assert on_disk == plan


def test_execute_verification_plan(verification_agent, mock_coding_tool,
                                    temp_plan_dir):
    # Phase 1 keeps automated_test / code_review / ui_validation /
    # api_test VPs and drops manual_check; pick automated_test so the
    # plan survives the filter. Monkey-patch the per-method executor
    # on the agent instance — the dispatcher detects the patch via
    # ``type(executor).__name__ == 'function'`` and uses the stub
    # instead of the canonical sub-agent path, which keeps the test
    # hermetic and independent of any LLM backend.
    mock_coding_tool.query_json.return_value = _build_plan_payload(
        methods=["code_review", "code_review"],
        priorities=["high", "medium"],
    )
    plan = verification_agent.generate_verification_plan()
    assert len(plan["verification_points"]) == 2

    _install_code_review_stub(verification_agent)

    results = verification_agent.execute_verification_plan(plan)

    assert isinstance(results, dict)
    assert "execution_results" in results
    assert "verification_points" in results
    assert isinstance(results["execution_results"], list)
    assert len(results["execution_results"]) == 2

    ids = [r.get("id") for r in results["execution_results"]]
    assert "VP-001" in ids
    assert "VP-002" in ids

    for r in results["execution_results"]:
        assert r.get("status") == "PASSED"
        assert "actual_result" in r

    # The agent persists the execution results so the report phase
    # can pick them up from SQLite (``plan_verification.execution_results``)
    # even when the caller does not pass them in. The legacy on-disk
    # cache at ``plans/{id}/verification_execution_results.json`` is
    # no longer written — see task #3.5.
    assert verification_agent.verif_repo is not None, (
        "expected verification_agent.verif_repo to be wired by the fixture"
    )
    stored = verification_agent.verif_repo.current(
        verification_agent.plan_dir.name
    )
    assert stored is not None
    assert stored.get("execution_results") == results


def test_generate_verification_report(verification_agent, mock_coding_tool,
                                      temp_plan_dir):
    # Drive execute_verification_plan with monkey-patched
    # ``_execute_automated_test`` so we don't need a real LLM /
    # sub-agent. The report generator still calls
    # ``coding_tool.query_json`` for the LLM-driven judgment.
    mock_coding_tool.query_json.return_value = _build_plan_payload(
        methods=["code_review", "code_review"],
        priorities=["high", "medium"],
    )
    plan = verification_agent.generate_verification_plan()
    _install_code_review_stub(verification_agent)
    execution_results = verification_agent.execute_verification_plan(plan)

    # The LLM-emitted report payload from Phase 3. Two VPs, one
    # PASSED, one FAILED, plus a requirement deviation entry. The
    # generator re-derives ``overall_status`` from the per-VP
    # statuses (see generate_verification_report in
    # backend/verification_agent.py), so what we assert against is
    # the final, post-rewrite state, not the raw LLM payload.
    mock_coding_tool.query_json.return_value = {
        "overall_status": "FAILED",
        "summary": "mixed verdicts",
        "verification_results": [
            {
                "id": "VP-001",
                "status": "PASSED",
                "actual_result": "ok",
                "reasons": [],
                "evidence": "",
            },
            {
                "id": "VP-002",
                "status": "FAILED",
                "actual_result": "missing feature X",
                "reasons": ["missing feature X"],
                "evidence": "X not found in code",
            },
        ],
        "requirement_deviations": [
            {
                "vp_id": "VP-002",
                "deviation_type": "missing",
                "severity": "high",
                "description": "missing feature X",
            },
        ],
    }

    report = verification_agent.generate_verification_report(execution_results)

    assert isinstance(report, dict)
    assert "overall_status" in report
    # FAILED is allowed because the LLM-emitted verdict list contains
    # at least one FAILED VP, and the post-rewrite logic preserves it.
    assert report["overall_status"] in {"PASSED", "FAILED", "LOOP_STOPPED"}

    # requirement_deviations must be a list (may be empty, but never
    # missing or a non-list).
    assert "requirement_deviations" in report
    assert isinstance(report["requirement_deviations"], list)
    assert report["requirement_deviations"]  # populated in this fixture

    # The per-VP results must be present and the count must match the
    # number of VPs we executed.
    assert "verification_results" in report
    assert isinstance(report["verification_results"], list)
    assert len(report["verification_results"]) == 2

    statuses = [vr.get("status") for vr in report["verification_results"]]
    passed = sum(1 for s in statuses if s == "PASSED")
    failed = sum(1 for s in statuses if s == "FAILED")
    skipped = sum(1 for s in statuses if s == "SKIPPED")
    assert passed + failed + skipped == len(report["verification_results"])

    # Report is persisted so downstream consumers can pick it up from
    # disk without re-running Phase 3.
    report_file = temp_plan_dir / "verification_report.json"
    assert report_file.exists()
    with open(report_file) as f:
        on_disk = json.load(f)
    assert on_disk == report


def test_plan_schema(verification_agent, mock_coding_tool):
    mock_coding_tool.query_json.return_value = _build_plan_payload(
        methods=["code_review", "ui_validation", "api_test",
                 "api_test"],
        priorities=["high", "medium", "low", "high"],
    )

    plan = verification_agent.generate_verification_plan()

    assert isinstance(plan["verification_points"], list)
    assert plan["verification_points"], "plan must contain at least one VP"

    for vp in plan["verification_points"]:
        for field in REQUIRED_VP_FIELDS:
            assert field in vp, f"VP {vp.get('id', '?')} missing field: {field}"

        assert isinstance(vp["id"], str)
        assert isinstance(vp["title"], str)
        assert isinstance(vp["related_prd_criteria"], str)
        assert isinstance(vp["verification_method"], str)
        assert isinstance(vp["priority"], str)
        assert isinstance(vp["expected_result"], str)

        assert vp["priority"] in VALID_PRIORITIES, (
            f"Invalid priority {vp['priority']!r} in VP {vp['id']}"
        )
        assert vp["verification_method"] in VALID_METHODS, (
            f"Invalid method {vp['verification_method']!r} in VP {vp['id']}"
        )

    # All VPs (including manual_check) survive Phase 1. The new
    # behavior keeps manual_check VPs in the plan and flags them
    # for human review, instead of dropping them. Non-manual_check
    # methods are still in KEPT_METHODS.
    for vp in plan["verification_points"]:
        assert vp["verification_method"] in VALID_METHODS



# ---------------------------------------------------------------------------
# 2026-09-18 — retired methods
#
# These replace the four ``manual_check`` Phase-1 tests. ``manual_check``
# and ``automated_test`` were retired that day, and the Phase-1 "keep vs
# drop" function they exercised was deleted with them. The invariant
# worth pinning now is that an unrunnable method is *retired*, not
# silently run or silently dropped: the VP stays in the plan, is marked
# ``obsolete`` with a reason, and the round logs it loudly.
# ---------------------------------------------------------------------------


def test_retired_method_vps_are_marked_obsolete(
    verification_agent, mock_coding_tool, temp_plan_dir
):
    for retired in ("automated_test", "manual_check"):
        payload = _build_plan_payload(
            methods=[retired, "code_review"], priorities=["high", "high"],
        )
        mock_coding_tool.query_json.return_value = payload
        (temp_plan_dir / "verification_plan.json").unlink(missing_ok=True)

        plan = verification_agent.generate_verification_plan()

        retired_vps = [
            vp for vp in plan["verification_points"]
            if vp.get("verification_method") == retired
        ]
        assert retired_vps, retired
        assert all(vp.get("obsolete") is True for vp in retired_vps), retired
        assert all(vp.get("obsolete_reason") for vp in retired_vps), retired


def test_supported_method_vps_are_not_marked_obsolete(
    verification_agent, mock_coding_tool, temp_plan_dir
):
    payload = _build_plan_payload(
        methods=["code_review", "ui_validation"], priorities=["high", "high"],
    )
    mock_coding_tool.query_json.return_value = payload
    (temp_plan_dir / "verification_plan.json").unlink(missing_ok=True)

    plan = verification_agent.generate_verification_plan()

    assert all(
        not vp.get("obsolete") for vp in plan["verification_points"]
    )


def test_a_vp_with_no_method_is_retired(
    verification_agent, mock_coding_tool, temp_plan_dir
):
    payload = _build_plan_payload(methods=["code_review"], priorities=["high"])
    del payload["verification_points"][0]["verification_method"]
    mock_coding_tool.query_json.return_value = payload
    (temp_plan_dir / "verification_plan.json").unlink(missing_ok=True)

    plan = verification_agent.generate_verification_plan()

    [vp] = plan["verification_points"]
    assert vp.get("obsolete") is True
    assert "missing" in vp.get("obsolete_reason", "")


def test_a_typo_method_is_retired(
    verification_agent, mock_coding_tool, temp_plan_dir
):
    payload = _build_plan_payload(methods=["codereview"], priorities=["high"])
    mock_coding_tool.query_json.return_value = payload
    (temp_plan_dir / "verification_plan.json").unlink(missing_ok=True)

    plan = verification_agent.generate_verification_plan()

    [vp] = plan["verification_points"]
    assert vp.get("obsolete") is True
    assert "not one of" in vp.get("obsolete_reason", "")
