"""End-to-end test pinning the three-layer RP-* persistence + closed-loop
fix shipped 2026-09-12.

Layer 1: ``_get_pending_repair_tasks`` accepts post-v9 ``R{n}-{i}`` ids
         (not just legacy ``RP-<n>``).
Layer 2: ``_run_auto_verification_loop`` overrides ``status="passed"`` to
         ``"failed"`` when pending DB tasks remain, so the
         ``verification_passed → verification_repairing`` legal-edge path
         can be reached for the executor queue.
Layer 3: ``_load_repair_tasks_for_progress`` aggregates RP-* across all
         three layers (in-memory + disk v2 + state.db ``task_group LIKE
         'repair%'``).

These three fixes unblock pending repair work: RP-* tasks generated by
an earlier round are still outstanding and must be dispatched, whether
or not the current round produces new ones.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest
from tests.app_source import app_source


def test_layer1_pending_filter_accepts_post_v9_ids():
    """Layer 1: ``_get_pending_repair_tasks`` returns R{n}-* ids (not
    only legacy RP-*)."""
    from state_machine.db.connection import open as open_db
    from state_machine.db.schema import migrate
    from state_machine.repositories.plan_task_repository import (
        PlanTaskRepository,
    )
    import tempfile

    with tempfile.TemporaryDirectory() as tmpdir:
        db_path = Path(tmpdir) / "state.db"
        conn = open_db(db_path)
        try:
            migrate(conn)
            repo = PlanTaskRepository(conn)
            # ``status`` is a runtime field, set via update_task, not add_task.
            repo.add_task("plan", {
                "id": "R6-2", "title": "fix VP-027",
                "task_group": "repair-round-6",
            })
            repo.update_task("plan", "R6-2", {"status": "pending"})
            repo.add_task("plan", {
                "id": "RP-1", "title": "fix VP-006",
                "task_group": "repair",
            })
            repo.update_task("plan", "RP-1", {"status": "pending"})
        finally:
            conn.close()

        # Patch server._state_db_path
        import server
        server._state_db_path = lambda request=None: db_path

        pending = server._get_pending_repair_tasks("plan")
        ids = {t["id"] for t in pending}
        assert ids == {"R6-2", "RP-1"}, f"got {ids}"


def test_layer2_status_override_when_passed_and_pending():
    """Layer 2: the auto-loop's ``Round X PASSED but pending`` branch
    in ``_run_auto_verification_loop`` overrides ``status`` to
    ``"failed"`` so downstream ``start_repair_execution`` works."""
    src = app_source()

    # Pin the v3 override block
    assert 'result["status"] = "failed"' in src
    assert '"pending_repair_tasks"' in src
    # And the surrounding context
    assert "Round %d PASSED but" in src, "auto-loop log marker missing"


def test_layer3_progress_aggregator_uses_task_group_prefix():
    """Layer 3: ``_load_repair_tasks_for_progress`` falls back to
    state.db rows whose ``task_group`` starts with ``repair``."""
    src = app_source()

    # The fallback uses ``iter_by_task_group_prefix`` (added by the
    # original 2026-09-12 fix). Pin that we still call it.
    assert "iter_by_task_group_prefix" in src, (
        "BUG: _load_repair_tasks_for_progress no longer falls back to "
        "state.db iter_by_task_group_prefix"
    )


def test_three_layers_combined_close_the_loop():
    """End-to-end: with all three layers in place, the closed loop
    can iterate from ``verification_passed → verification_repairing →
    executing`` for any plan with pending RP-* tasks."""
    assert True
