"""Cross-component exit point: the watchdog signal file.

Architecture decision point 3 (refiner exhausts 3 rounds), decision
point 4 (dispatcher auto_fix still fails) and decision point 6
(watchdog validate-through fails) all funnel through this one file.
Each caller writes the same shape and the same path; the watchdog
then ``read_signal``-s the file in its single retry loop.

File shape
----------

``plans/{plan_id}/_watchdog_signal.json``::

    {
        "schema_version": "1",
        "plan_id": "<plan_id>",
        "source": "refiner" | "dispatcher" | "watchdog",
        "reason": "<human readable reason>",
        "detail": { ...arbitrary structured detail... },
        "created_at": "<ISO-8601 UTC, microsecond precision>"
    }

Atomicity
---------

The file is written ``tmp + os.replace`` so a concurrent reader
never sees a half-written file. The ``os.replace`` rename is
atomic on POSIX (and on Windows when the destination is on the
same volume), so any reader either sees the previous complete
version or the new complete version — never a mix.

Path safety
-----------

The ``plan_id`` is funneled through :func:`framework.ids.validate_plan_id`
so the same ``..`` / absolute-path / path-separator guards apply
as everywhere else that touches ``plans/{plan_id}``.

Clock source
------------

``created_at`` is generated by :func:`framework.clock.utcnow_iso`,
the single timestamp injection point mandated by architecture
decision point 5. Tests freeze the clock by monkeypatching
``framework.clock.utcnow_iso`` directly.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any, Final, Literal

import jsonschema

from framework.clock import utcnow_iso
from framework.ids import validate_plan_id

__all__ = [
    "SIGNAL_SCHEMA",
    "SIGNAL_FILENAME",
    "SIGNAL_SOURCES",
    "read_signal",
    "write_signal",
]


# ---------------------------------------------------------------------------
# Public constants
# ---------------------------------------------------------------------------

#: Name of the signal file inside ``plans/{plan_id}/``.
SIGNAL_FILENAME: Final[str] = "_watchdog_signal.json"

#: Allowed values for the ``source`` field.
SIGNAL_SOURCES: Final[frozenset[str]] = frozenset(
    {"refiner", "dispatcher", "watchdog"}
)

#: Current schema version of the on-disk signal file. Bump whenever
#: the schema changes in a backwards-incompatible way.
SIGNAL_SCHEMA_VERSION: Final[str] = "1"

#: The signal file's JSON schema. ``jsonschema.validate`` is called
#: on both the writer side (before serialise) and the reader side
#: (after deserialise) so a corrupted file never silently slips into
#: the watchdog's retry loop.
SIGNAL_SCHEMA: Final[dict[str, Any]] = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "WatchdogSignal",
    "type": "object",
    "required": [
        "schema_version",
        "plan_id",
        "source",
        "reason",
        "detail",
        "created_at",
    ],
    "additionalProperties": False,
    "properties": {
        "schema_version": {
            "type": "string",
            # We pin the version so the watchdog can downgrade-handle
            # older files written by older writers.
            "const": SIGNAL_SCHEMA_VERSION,
        },
        "plan_id": {
            "type": "string",
            "minLength": 1,
        },
        "source": {
            "type": "string",
            # We deliberately use ``enum`` rather than a regex — the
            # schema is the source of truth for the closed set, so a
            # typo here is caught immediately.
            "enum": sorted(SIGNAL_SOURCES),
        },
        "reason": {
            "type": "string",
            "minLength": 1,
        },
        "detail": {
            # Anything JSON-serialisable — callers pass dicts, lists,
            # primitives; we serialise through json.dumps so the type
            # constraints are enforced at write time, not at read time.
            "type": "object",
        },
        "created_at": {
            "type": "string",
            # ISO-8601 with explicit UTC offset (e.g.
            # ``2026-08-07T10:11:12.345678+00:00``).
            "pattern": r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?\+00:00$",
        },
    },
}

#: Path to the ``plans/`` directory. Writers compute the destination
#: as ``PLANS_ROOT / plan_id / SIGNAL_FILENAME``. Tests monkeypatch
#: this to a ``tmp_path`` so they don't touch the real on-disk plans.
PLANS_ROOT: Final[Path] = Path("plans")


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


# Re-export the plan-id error so callers don't have to import the
# framework.ids module separately when they only need the signal
# surface.
from framework.ids import InvalidPlanIdError  # noqa: E402  (import at module level for re-export)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_signal(
    plan_id: str,
    source: Literal["refiner", "dispatcher", "watchdog"],
    reason: str,
    detail: dict[str, Any],
) -> Path:
    """Write ``plans/{plan_id}/_watchdog_signal.json`` atomically.

    Parameters
    ----------
    plan_id:
        Identifies the plan whose the backend wrote the signal. Must
        be a safe filesystem leaf (see :func:`framework.ids.validate_plan_id`).
    source:
        Which subsystem raised the signal. Must be one of
        ``"refiner"``, ``"dispatcher"``, ``"watchdog"``.
    reason:
        Human-readable summary suitable for logs and dashboards.
    detail:
        Arbitrary structured context — refiner round counts,
        validation error lists, retry attempt numbers, etc. Must
        be JSON-serialisable.

    Returns
    -------
    pathlib.Path
        The final destination path (suitable for logging).

    Raises
    ------
    InvalidPlanIdError
        If ``plan_id`` is unsafe (``..`` traversal, absolute path,
        path separator, etc.).
    ValueError
        If ``source`` is not one of the three declared enum values
        OR ``reason`` is empty OR ``detail`` is not a dict.
    jsonschema.ValidationError
        If the constructed payload fails ``SIGNAL_SCHEMA`` (a
        programmer-error guard that should be impossible to hit in
        normal use).
    OSError
        If the filesystem write itself fails (e.g. permission
        denied, disk full). The atomic tmp+rename guarantees we
        never leave a half-written file in that case.
    """
    safe_id = validate_plan_id(plan_id)

    if source not in SIGNAL_SOURCES:
        # Closed-enum guard. The Literal type already enforces this at
        # type-check time, but we re-check at runtime so the public
        # contract is bullet-proof for callers that pass through
        # ``**kwargs`` or untyped dicts.
        raise ValueError(
            f"source must be one of {sorted(SIGNAL_SOURCES)}; got {source!r}"
        )
    if not isinstance(reason, str) or not reason:
        raise ValueError("reason must be a non-empty string")
    if not isinstance(detail, dict):
        raise ValueError(
            f"detail must be a dict; got {type(detail).__name__}"
        )

    payload: dict[str, Any] = {
        "schema_version": SIGNAL_SCHEMA_VERSION,
        "plan_id": safe_id,
        "source": source,
        "reason": reason,
        "detail": detail,
        "created_at": utcnow_iso(),
    }

    # Defensive schema check on the way out: if the literal above
    # ever drifts out of sync with ``SIGNAL_SCHEMA`` we want to
    # catch it BEFORE the rename so a corrupted file never lands
    # on disk.
    jsonschema.validate(payload, SIGNAL_SCHEMA)

    target_dir = PLANS_ROOT / safe_id
    target = target_dir / SIGNAL_FILENAME
    target_dir.mkdir(parents=True, exist_ok=True)

    # Atomic tmp + rename. ``NamedTemporaryFile(delete=False, dir=target_dir)``
    # keeps the tmp file on the same filesystem as the destination so
    # ``os.replace`` is atomic; we manually unlink the tmp file in a
    # ``finally`` so an interrupted write doesn't litter the plan dir.
    fd, tmp_path_str = tempfile.mkstemp(
        prefix=".watchdog_signal.", suffix=".json.tmp", dir=str(target_dir)
    )
    tmp_path = Path(tmp_path_str)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, ensure_ascii=False, sort_keys=False)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_path, target)
    except Exception:
        # Best-effort cleanup if the rename failed. We deliberately
        # re-raise so the caller sees the underlying error.
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise

    return target


def read_signal(plan_id: str) -> dict[str, Any] | None:
    """Read and validate ``plans/{plan_id}/_watchdog_signal.json``.

    Parameters
    ----------
    plan_id:
        Same id that was passed to :func:`write_signal`. Validated
        with the same guards, so traversal / absolute paths raise
        :class:`InvalidPlanIdError` even on the read path (defence
        in depth — the watchdog must not accidentally read a file
        outside the plan root).

    Returns
    -------
    dict | None
        The parsed payload on success, or ``None`` if the file does
        not exist.

    Raises
    ------
    InvalidPlanIdError
        If ``plan_id`` is unsafe.
    jsonschema.ValidationError
        If the file exists but does not match ``SIGNAL_SCHEMA``.
        A corrupted file is a hard failure: we never silently
        return malformed data to the watchdog.
    """
    safe_id = validate_plan_id(plan_id)

    target = PLANS_ROOT / safe_id / SIGNAL_FILENAME
    if not target.exists():
        return None

    payload = json.loads(target.read_text(encoding="utf-8"))
    # Validate on the read path: a writer bug (or an external
    # editor) could leave a structurally invalid file behind. The
    # watchdog MUST see the failure explicitly rather than silently
    # acting on malformed data.
    jsonschema.validate(payload, SIGNAL_SCHEMA)
    return payload


# ---------------------------------------------------------------------------
# Internal helpers (kept private; only exposed for tests via the
# module's __dict__ so a future TDD case can extend the contract
# without breaking the public surface).
# ---------------------------------------------------------------------------

# Pattern used by SIGNAL_SCHEMA's ``created_at`` property — kept as
# a module-level ``re`` object so the regex is compiled once at
# import time.
_ISO8601_UTC_PATTERN: Final[re.Pattern[str]] = re.compile(
    SIGNAL_SCHEMA["properties"]["created_at"]["pattern"]
)